#!/bin/sh
echo Starting Cron...
service cron start
echo Starting PHP-FPM...
service php7.2-fpm start
echo Starting NGINX...
service nginx start
nginx -v
echo Attempting Certificate renewall...
certbot renew
echo Running!
tail -f /dev/null
